services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ../data:/app/data

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
